server:
  error:
    include-message: always
  max-http-header-size: 40KB
  port: 8080

management:
  server:
    port: 8081
  endpoint:
    health.show-details: always
  endpoints:
    web:
      exposure:
        include: "health"