kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        version: v1
    spec:
      volumes:
        - name: {{ .Values.app.name }}-properties
          configMap:
            name: {{ .Values.app.name }}-properties
            items:
              - key: application-config
                path: application-config
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pull.policy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe: {{- omit .Values.startupProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe: {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe: {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ .Values.app.name }}-properties
              mountPath: /app/config/application.yml
              subPath: application-config
      imagePullSecrets:
        - name: {{ .Values.image.pull.secrets }}