kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  host: {{ .Values.app.name }}-{{ .Values.deploy.namespace }}.{{ .Values.deploy.host}}
  to:
    kind: Service
    name: {{ .Values.app.name }}
    weight: 100
  port:
    targetPort: http