kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
