image:
  repository: works.v-serv.ru:444
  name: sandbox-docker/gt_sandbox_21_docker/helloplatform
  tag: 0.2
  pull:
    policy: Always
    secrets: tuz-bootcamp-sandbox

app:
  name: helloplatform
  conf:
    spring:
      ufs:
        url: http://ufs-provider-gt-sol-dev-coreplatform-01.apps.ocp.dvpdev.tech/ufs-provider

deploy:
  namespace: test
  host: apps.ocp.test.bootcamp.tech

resources:
  limits:
    cpu: 200m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 512Mi

startupProbe:
  enabled: true
  httpGet:
    path: /api/actuator/health
    port: 8080
    scheme: HTTP
  periodSeconds: 15
  timeoutSeconds: 3
  failureThreshold: 6
  initialDelaySeconds: 60

readinessProbe:
  enabled: true
  httpGet:
    path: /api/actuator/health
    port: 8080
    scheme: HTTP
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 3
  initialDelaySeconds: 5

livenessProbe:
  enabled: true
  httpGet:
    path: /api/actuator/health
    port: 8080
    scheme: HTTP
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 3
  initialDelaySeconds: 5